export const UPLOAD_DRIVER_DOCS = 'UPLOAD_DRIVER_DOCS';
export const UPLOAD_DRIVER_DOCS_SUCCESS = `${UPLOAD_DRIVER_DOCS}_SUCCESS`;
export const UPLOAD_DRIVER_DOCS_FAILURE = `${UPLOAD_DRIVER_DOCS}_FAILURE`;