export const UPLOAD_DRIVER_DOCS = 'UPLOAD_DRIVER_DOCS';
export const UPLOAD_DRIVER_DOCS_SUCCESS = `${UPLOAD_DRIVER_DOCS}_SUCCESS`;
export const UPLOAD_DRIVER_DOCS_FAILURE = `${UPLOAD_DRIVER_DOCS}_FAILURE`;

export const UPLOAD_DOCS_FOR_CHANGE = 'UPLOAD_DOCS_FOR_CHANGE';
export const UPLOAD_DOCS_FOR_CHANGE_SUCCESS = `${UPLOAD_DOCS_FOR_CHANGE}_SUCCESS`;
export const UPLOAD_DOCS_FOR_CHANGE_FAILURE = `${UPLOAD_DOCS_FOR_CHANGE}_FAILURE`;