export const LOG_IN = 'LOG_IN';
export const LOG_IN_SUCCESS = `${LOG_IN}_SUCCESS`;
export const LOG_IN_FAILURE = `${LOG_IN}_FAILURE`;

export const LOG_OUT = 'LOG_OUT';
export const LOG_OUT_SUCCESS = `${LOG_OUT}_SUCCESS`;
export const LOG_OUT_FAILURE = `${LOG_OUT}_FAILURE`;

export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_SUCCESS = `${SIGN_UP}_SUCCESS`;
export const SIGN_UP_FAILURE = `${SIGN_UP}_FAILURE`;

export const RESTORE_PASSWORD = 'RESTORE_PASSWORD';
export const RESTORE_PASSWORD_SUCCESS = `${RESTORE_PASSWORD}_SUCCESS`;
export const RESTORE_PASSWORD_FAILURE = `${RESTORE_PASSWORD}_FAILURE`;

export const VERIFY_TOKEN = 'VERIFY_TOKEN';
export const VERIFY_TOKEN_SUCCESS = `${VERIFY_TOKEN}_SUCCESS`;
export const VERIFY_TOKEN_FAILURE = `${VERIFY_TOKEN}_FAILURE`;

export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const FORGOT_PASSWORD_SUCCESS = `${FORGOT_PASSWORD}_SUCCESS`;
export const FORGOT_PASSWORD_FAILURE = `${FORGOT_PASSWORD}_FAILURE`;

