export const VIEW_DRIVER_PROFILE = 'VIEW_DRIVER_PROFILE';
export const VIEW_DRIVER_PROFILE_SUCCESS = `${VIEW_DRIVER_PROFILE}_SUCCESS`;
export const VIEW_DRIVER_PROFILE_FAILURE = `${VIEW_DRIVER_PROFILE}_FAILURE`;

export const VERIFY_INFORMATION = 'VERIFY_INFORMATION';
export const VERIFY_INFORMATION_SUCCESS = `${VERIFY_INFORMATION}_SUCCESS`;
export const VERIFY_INFORMATION_FAILURE = `${VERIFY_INFORMATION}_FAILURE`;

export const REQUEST_CHANGES = 'REQUEST_CHANGES';
export const REQUEST_CHANGES_SUCCESS = `${REQUEST_CHANGES}_SUCCESS`;
export const REQUEST_CHANGES_FAILURE = `${REQUEST_CHANGES}_FAILURE`;
